// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-imk9dkuNEJ8JydRhz7Tt8VDtifbrRk',
    appId: '1:653151342963:web:1ea9ea73b8b75b1a66b506',
    messagingSenderId: '653151342963',
    projectId: 'keja-e5d42',
    authDomain: 'keja-e5d42.firebaseapp.com',
    storageBucket: 'keja-e5d42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfObQxiPl_jpNKcomEGUjRFPq7abg9zDs',
    appId: '1:653151342963:android:c4e01edd81d4912c66b506',
    messagingSenderId: '653151342963',
    projectId: 'keja-e5d42',
    storageBucket: 'keja-e5d42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU-DUZNlIBj4KEtNuaPHzeNfSop2eqPKE',
    appId: '1:653151342963:ios:ac432cf2f1d7320766b506',
    messagingSenderId: '653151342963',
    projectId: 'keja-e5d42',
    storageBucket: 'keja-e5d42.appspot.com',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU-DUZNlIBj4KEtNuaPHzeNfSop2eqPKE',
    appId: '1:653151342963:ios:ac432cf2f1d7320766b506',
    messagingSenderId: '653151342963',
    projectId: 'keja-e5d42',
    storageBucket: 'keja-e5d42.appspot.com',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUHvbF-1yNjnmoQChLn6nUdkoazvOmAwM',
    appId: '1:653151342963:web:97b6233cef924ce866b506',
    messagingSenderId: '653151342963',
    projectId: 'keja-e5d42',
    authDomain: 'keja-e5d42.firebaseapp.com',
    storageBucket: 'keja-e5d42.appspot.com',
  );

}